'use strict';

export const restsArray = [
  {
    id: 0,
    image: 'pizza_plus_2x.webp',
    alt: 'Pizza Plus',
    name: 'Пицца Плюс',
    time: 50,
    rating: 4.5,
    price: 900,
    tags: ['Пицца', 'Роллы'],
  },
  {
    id: 1,
    image: 'tanuki_2x.webp',
    alt: 'Tanuki',
    name: 'Тануки',
    time: 50,
    rating: 4.5,
    price: 900,
    tags: ['Роллы', 'Суши', 'Wok'],
  },
  {
    id: 2,
    image: 'foodband_2x.webp',
    alt: 'FoodBand',
    name: 'FoodBand',
    time: 50,
    rating: 4.5,
    price: 900,
    tags: ['Пицца', 'Роллы', 'Суши', 'Wok'],
  },
  {
    id: 3,
    image: 'zhadina-pizza_2x.webp',
    alt: 'Zhadina pizza',
    name: 'Жадина Пицца',
    time: 50,
    rating: 4.5,
    price: 900,
    tags: ['Пицца', 'Суши'],
  },
  {
    id: 4,
    image: 'food_point_2x.webp',
    alt: 'Food point',
    name: 'Точка еды',
    time: 50,
    rating: 4.5,
    price: 900,
    tags: ['Пицца', 'Роллы', 'Wok'],
  },
  {
    id: 5,
    image: 'pizzaburger_2x.webp',
    alt: 'PizzaBurger',
    name: 'PizzaBurger',
    time: 50,
    rating: 4.5,
    price: 900,
    tags: ['Пицца'],
  },
];
